#!/usr/bin/env bash
# Export packages/core → policy_snapshot.json + Chromium C++ .inc overlays.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

CORE_DIR="$REPO_ROOT/packages/core"
OVERLAY_POLICY="$ROOT_DIR/overlay/third_party/aegis_policy"
OVERLAY_GEN="$ROOT_DIR/overlay/chrome/common/aegis/generated"
SNAPSHOT="$OVERLAY_POLICY/policy_snapshot.json"

mkdir -p "$OVERLAY_POLICY" "$OVERLAY_GEN"

echo "Exporting policy snapshot…"
node "$CORE_DIR/scripts/export-snapshot.mjs" "$SNAPSHOT"

export SNAPSHOT OVERLAY_GEN OVERLAY_POLICY
python3 <<'PY'
import json
import os
from pathlib import Path

snapshot = json.loads(Path(os.environ["SNAPSHOT"]).read_text())
gen = Path(os.environ["OVERLAY_GEN"])
gen.mkdir(parents=True, exist_ok=True)

def write_inc(name: str, values: list[str], var: str) -> None:
    lines = [
        "// Generated by apps/browser/scripts/sync-core-snapshot.sh — do not edit.",
        f"// Source: packages/core → {name}",
        f"constexpr std::string_view {var}[] = {{",
    ]
    for v in values:
        escaped = v.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{escaped}",')
    lines.append("};")
    lines.append("")
    path = gen / name
    path.write_text("\n".join(lines))
    print(f"Wrote {path} ({len(values)} entries)")

write_inc("tracker_hosts.inc", snapshot["trackerHosts"], "kBuiltinTrackerRules")
write_inc("phish_hosts.inc", snapshot["phishHosts"], "kBuiltinPhishRules")
write_inc(
    "tracking_query_params.inc",
    snapshot["trackingQueryParams"],
    "kTrackingQueryParams",
)
write_inc(
    "first_party_collect_paths.inc",
    snapshot["firstPartyCollectPaths"],
    "kFirstPartyCollectPaths",
)
write_inc(
    "phish_brand_keywords.inc",
    snapshot["phishBrandKeywords"],
    "kPhishBrandKeywords",
)
write_inc(
    "suspicious_phish_tlds.inc",
    snapshot["suspiciousTlds"],
    "kSuspiciousPhishTlds",
)

readme = Path(os.environ["OVERLAY_POLICY"]) / "README.md"
readme.write_text(
    """# third_party/aegis_policy

Policy snapshot exported from `packages/core`.

| File | Role |
|------|------|
| `policy_snapshot.json` | Portable JSON (trackers / phish seeds / params / collect paths) |
| `policy_worker.js` | Bundled `packages/core` JS policy worker (IIFE) |
| `easylist_compiled.json` | Optional local compile of EasyList (gitignored, GPL/CC) |
| `../chrome/common/aegis/generated/*.inc` | C++ string tables included by builtin_*.cc |
| `../chrome/browser/aegis/generated/policy_worker_source.inc` | C++ raw-string of `policy_worker.js` |

Regenerate:

```bash
pnpm --filter @gcsa-aegis/browser sync-core-snapshot
pnpm --filter @gcsa-aegis/browser sync-policy-worker
pnpm --filter @gcsa-aegis/browser sync-easylist   # optional; runtime updater also fetches
```

Do not hand-edit generated `.inc` files — edit TypeScript under `packages/core` instead.
"""
)
print(f"Wrote {readme}")
PY

echo "Done. Next: apply overlay into Chromium (or seed a new patch)."
