#!/usr/bin/env bash
# Bundle packages/core policy worker → overlay JS + C++ string literal.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

CORE_DIR="$REPO_ROOT/packages/core"
OVERLAY_POLICY="$ROOT_DIR/overlay/third_party/aegis_policy"
OVERLAY_GEN="$ROOT_DIR/overlay/chrome/browser/aegis/generated"
OVERLAY_WEBUI="$ROOT_DIR/overlay/chrome/browser/resources/aegis"
OUT_JS="$OVERLAY_POLICY/policy_worker.js"
OUT_INC="$OVERLAY_GEN/policy_worker_source.inc"
OUT_TS="$OVERLAY_WEBUI/policy_worker.ts"

mkdir -p "$OVERLAY_POLICY" "$OVERLAY_GEN" "$OVERLAY_WEBUI"

echo "Bundling packages/core policy worker…"
pnpm --filter @gcsa-aegis/core bundle-policy-worker

BUNDLE="$(ls "$CORE_DIR"/dist-worker/*.js | head -1)"
if [[ ! -f "$BUNDLE" ]]; then
  echo "Missing tsup output under $CORE_DIR/dist-worker"
  exit 1
fi

cp "$BUNDLE" "$OUT_JS"
echo "Wrote $OUT_JS ($(wc -c < "$OUT_JS" | tr -d ' ') bytes)"

export OUT_JS OUT_INC OUT_TS
python3 <<'PY'
from pathlib import Path
import os

js = Path(os.environ["OUT_JS"]).read_text()
if ")AEGISJS" in js:
    raise SystemExit("bundled JS contains delimiter )AEGISJS")
inc = Path(os.environ["OUT_INC"])
inc.write_text(
    "// Generated by apps/browser/scripts/sync-policy-worker.sh — do not edit.\n"
    "// Source: packages/core/src/policy-worker-entry.ts\n"
    "inline constexpr char kAegisPolicyWorkerJs[] = R\"AEGISJS(\n"
    + js
    + "\n)AEGISJS\";\n"
)
print(f"Wrote {inc} ({inc.stat().st_size} bytes)")

# WebUI 不能把裸 .js 放进 static_files；包成 TS 模块给 chrome://aegis 加载。
ts = Path(os.environ["OUT_TS"])
ts.write_text(
    "// Copyright 2026 GCSA\n"
    "// Generated by apps/browser/scripts/sync-policy-worker.sh — do not edit.\n"
    "// @ts-nocheck\n"
    + js.rstrip()
    + "\n\nexport {};\n"
)
print(f"Wrote {ts} ({ts.stat().st_size} bytes)")
PY

echo "Done. Next: copy overlay into Chromium and land a patch."
