# Copyright 2026 GCSA
# Intended path: chrome/browser/resources/aegis/BUILD.gn

import("//ui/webui/resources/tools/build_webui.gni")

build_webui("build") {
  grd_prefix = "aegis"
  static_files = [
    "aegis.css",
    "aegis.html",
    "gestures.html",
    "gestures.css",
    "product_logo.svg",
  ]
  ts_files = [
    "aegis.ts",
    "gestures.ts",
    "policy_worker.ts",
  ]

  ts_deps = [
    "//ui/webui/resources/cr_components/aegis_downloads:build_ts",
    "//ui/webui/resources/js:build_ts",
  ]
  ts_definitions = [ "//tools/typescript/definitions/chrome_send.d.ts" ]
  webui_context_type = "trusted"
}
